# Generated by Django 4.1.3 on 2024-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuspassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pswrd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
