# Generated by Django 5.1.1 on 2024-11-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuspassApp', '0002_customuser_pswrd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instreg',
            name='usr_con',
        ),
        migrations.RemoveField(
            model_name='studreg',
            name='inst_id',
        ),
        migrations.RemoveField(
            model_name='studreg',
            name='usr_con',
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('usr_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DipoReg',
        ),
        migrations.DeleteModel(
            name='InstReg',
        ),
        migrations.DeleteModel(
            name='StudReg',
        ),
    ]
